name: release

on:
  push:
    tags:
      - v1.*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'

      - name: Get tag version
        id: version
        uses: battila7/get-version-action@v2

      - name: Create release artifacts
        run: ./gradlew -Pversion=${{ steps.version.outputs.version-without-v }} jar sourcesJar jarWithDependencies dokkaJavadocJar

      - name: Create release and upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          name: Lingua ${{ steps.version.outputs.version-without-v }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
